# Generated by Django 5.1.1 on 2026-05-13 09:31

import apps.core.constants
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('structure', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'slide_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('secondary_color', models.CharField(default='#ffffff', max_length=7)),
                ('accent_color', models.CharField(default='#0066cc', max_length=7)),
                ('font_heading', models.CharField(default='Arial', max_length=100)),
                ('font_body', models.CharField(default='Arial', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'themes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_public', models.BooleanField(default=False)),
                ('slide_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations', to='presentations.theme')),
            ],
            options={
                'db_table': 'presentations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heading', models.CharField(blank=True, default='', max_length=500)),
                ('body', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('layout', models.CharField(choices=[('title', 'TITLE'), ('content', 'CONTENT'), ('two_column', 'TWO_COLUMN'), ('image_left', 'IMAGE_LEFT'), ('image_right', 'IMAGE_RIGHT'), ('blank', 'BLANK')], default=apps.core.constants.SlideLayout['CONTENT'], max_length=50)),
                ('position', models.PositiveIntegerField(default=0)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='presentations.presentation')),
            ],
            options={
                'db_table': 'slides',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['presentation', 'position'], name='slides_present_2b39d6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='presentation',
            index=models.Index(fields=['owner', '-updated_at'], name='presentatio_owner_i_26a292_idx'),
        ),
    ]
