# Generated by Django 5.1.1 on 2026-05-31 13:41

import apps.core.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='body',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='layout',
        ),
        migrations.AddField(
            model_name='slide',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_type',
            field=models.CharField(choices=[('cover', 'COVER'), ('split', 'SPLIT'), ('closing', 'CLOSING')], default=apps.core.constants.SlideType['SPLIT'], max_length=20),
        ),
    ]
